# Generated by Django 2.1.5 on 2020-02-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_kind_pizza_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('orders', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
